name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
      - name: Install dependencies
        id: install
        run: |
          make install
      - name: Run Tests
        id: test
        run: |
          make test > test-output.md   
      - name: Copy Test Output to Reports
        run: cp test-output.md reports/test_output.md
